syslog
#new-log-timestamp
no-rfc5780
no-stun-backward-compatibility
listening-port=3478
tls-listening-port=5349
use-auth-secret
static-auth-secret="<LONG_SECRET_KEY>"
realm=turn.<example.com>
server-name=coturn
min-port=49000
max-port=50000
verbose
#allow-loopback-peers
#allowed-peer-ip=0.0.0.0-255.255.255.255
cli-password=SomePasswordForCLI
external-ip=<YOUR_SERVER_IP>
fingerprint
#user=test:test123
lt-cred-mech
#cert=/certs/turn-cert.pem
#pkey=/certs/turn-privkey.pem
